<?php

declare(strict_types=1);

use Phinx\Seed\AbstractSeed;

class BookSeeder extends AbstractSeed
{
    public function run(): void
    {
        // Limpiar la tabla antes de insertar para evitar duplicados al re-ejecutar
        $this->execute('DELETE FROM books');

        $data = [
            [
                'title'          => 'El Aleph',
                'author'         => 'Jorge Luis Borges',
                'price'          => 15000.00,
                'description'    => 'Una de las obras maestras de la literatura universal.',
                'stock'          => 10,
                'image'          => 'libros/aleph.jpg',
                'category'       => 'fantasia',
                'age'            => 'adulto',
                'is_new'         => true,
                'discount'       => 10.00,
                'is_recommended' => true,
            ],
            [
                'title'          => 'Rayuela',
                'author'         => 'Julio Cortázar',
                'price'          => 18500.00,
                'description'    => 'Una novela que se puede leer de muchas maneras.',
                'stock'          => 5,
                'image'          => 'libros/rayuela.jpg',
                'category'       => 'fantasia',
                'age'            => 'adulto',
                'is_new'         => false,
                'discount'       => 0.00,
                'is_recommended' => true,
            ],
            [
                'title'          => 'Cien años de soledad',
                'author'         => 'Gabriel García Márquez',
                'price'          => 22000.00,
                'description'    => 'La saga de la familia Buendía en Macondo.',
                'stock'          => 8,
                'image'          => 'libros/soledad.jpg',
                'category'       => 'fantasia',
                'age'            => 'adulto',
                'is_new'         => true,
                'discount'       => 15.00,
                'is_recommended' => false,
            ],
            [
                'title'          => 'Fundación',
                'author'         => 'Isaac Asimov',
                'price'          => 12500.00,
                'description'    => 'El inicio de la saga épica sobre la caída y resurgimiento de la civilización galáctica.',
                'stock'          => 15,
                'image'          => 'libros/fundacion.jpg',
                'category'       => 'ciencia-ficcion',
                'age'            => 'adulto',
                'is_new'         => false,
                'discount'       => 5.00,
                'is_recommended' => true,
            ],
            [
                'title'          => 'Orgullo y Prejuicio',
                'author'         => 'Jane Austen',
                'price'          => 9800.00,
                'description'    => 'La historia de Elizabeth Bennet y el señor Darcy en la Inglaterra del siglo XIX.',
                'stock'          => 20,
                'image'          => 'libros/orgullo-y-prejuicio.jpg',
                'category'       => 'romance',
                'age'            => 'juvenil',
                'is_new'         => true,
                'discount'       => 0.00,
                'is_recommended' => true,
            ],
            [
                'title'          => 'La isla del tesoro',
                'author'         => 'Robert Louis Stevenson',
                'price'          => 7500.00,
                'description'    => 'La aventura clásica de piratas, mapas y tesoros escondidos.',
                'stock'          => 12,
                'image'          => 'libros/isla-del-tesoro.jpg',
                'category'       => 'aventura',
                'age'            => 'juvenil',
                'is_new'         => false,
                'discount'       => 20.00,
                'is_recommended' => false,
            ],
            [
                'title'          => 'El nombre del viento',
                'author'         => 'Patrick Rothfuss',
                'price'          => 19900.00,
                'description'    => 'La historia de Kvothe, contada por él mismo al Cronista.',
                'stock'          => 0,
                'image'          => 'libros/nombre-del-viento.jpg',
                'category'       => 'fantasia',
                'age'            => 'adulto',
                'is_new'         => false,
                'discount'       => 0.00,
                'is_recommended' => true,
            ],
            [
                'title'          => 'Sherlock Holmes: Estudio en escarlata',
                'author'         => 'Arthur Conan Doyle',
                'price'          => 6800.00,
                'description'    => 'La primera novela del detective más famoso de la literatura.',
                'stock'          => 25,
                'image'          => 'libros/sherlock-holmes-escarlata.jpg',
                'category'       => 'misterio',
                'age'            => 'juvenil',
                'is_new'         => false,
                'discount'       => 10.00,
                'is_recommended' => false,
            ],
            [
                'title'          => 'Sapiens: De animales a dioses',
                'author'         => 'Yuval Noah Harari',
                'price'          => 24000.00,
                'description'    => 'Una breve historia de la humanidad desde sus orígenes.',
                'stock'          => 7,
                'image'          => 'libros/sapiens.jpg',
                'category'       => 'historia',
                'age'            => 'adulto',
                'is_new'         => true,
                'discount'       => 0.00,
                'is_recommended' => false,
            ],
            [
                'title'          => 'El Principito',
                'author'         => 'Antoine de Saint-Exupéry',
                'price'          => 5500.00,
                'description'    => 'Un clásico atemporal sobre la amistad, el amor y la pérdida.',
                'stock'          => 30,
                'image'          => 'libros/principito.jpg',
                'category'       => 'fantasia',
                'age'            => 'infantil',
                'is_new'         => false,
                'discount'       => 0.00,
                'is_recommended' => true,
            ],
            [
                'title'          => 'Dune',
                'author'         => 'Frank Herbert',
                'price'          => 21000.00,
                'description'    => 'Una epopeya de ciencia ficción ambientada en el desierto planeta Arrakis.',
                'stock'          => 3,
                'image'          => 'libros/dune.jpg',
                'category'       => 'ciencia-ficcion',
                'age'            => 'adulto',
                'is_new'         => true,
                'discount'       => 12.00,
                'is_recommended' => true,
            ],
            [
                'title'          => 'Matilda',
                'author'         => 'Roald Dahl',
                'price'          => 4200.00,
                'description'    => 'La historia de una niña extraordinaria con poderes telequinéticos.',
                'stock'          => 18,
                'image'          => 'libros/matilda.jpg',
                'category'       => 'fantasia',
                'age'            => 'infantil',
                'is_new'         => false,
                'discount'       => 25.00,
                'is_recommended' => false,
            ],
            [
                'title'          => 'Cosmos',
                'author'         => 'Carl Sagan',
                'price'          => 16500.00,
                'description'    => 'Un viaje por el universo de la mano de uno de los grandes divulgadores científicos.',
                'stock'          => 0,
                'image'          => 'libros/cosmos.jpg',
                'category'       => 'no-ficcion',
                'age'            => 'adulto',
                'is_new'         => false,
                'discount'       => 0.00,
                'is_recommended' => false,
            ],
            [
                'title'          => 'Harry Potter y la piedra filosofal',
                'author'         => 'J.K. Rowling',
                'price'          => 11000.00,
                'description'    => 'El comienzo de la saga del joven mago más famoso del mundo.',
                'stock'          => 40,
                'image'          => 'libros/harry-potter-piedra-filosofal.jpg',
                'category'       => 'fantasia',
                'age'            => 'juvenil',
                'is_new'         => true,
                'discount'       => 0.00,
                'is_recommended' => true,
            ],
            [
                'title'          => 'Los viajes de Gulliver',
                'author'         => 'Jonathan Swift',
                'price'          => 8200.00,
                'description'    => 'Las fantásticas aventuras del capitán Lemuel Gulliver por tierras desconocidas.',
                'stock'          => 6,
                'image'          => 'libros/gulliver.jpg',
                'category'       => 'aventura',
                'age'            => 'juvenil',
                'is_new'         => false,
                'discount'       => 8.00,
                'is_recommended' => false,
            ],
            [
                'title'          => 'Breve historia del tiempo',
                'author'         => 'Stephen Hawking',
                'price'          => 13800.00,
                'description'    => 'Una introducción accesible a los grandes misterios del universo.',
                'stock'          => 9,
                'image'          => 'libros/breve-historia-del-tiempo.jpg',
                'category'       => 'no-ficcion',
                'age'            => 'adulto',
                'is_new'         => false,
                'discount'       => 0.00,
                'is_recommended' => true,
            ],
            [
                'title'          => 'Caperucita Roja (ilustrado)',
                'author'         => 'Charles Perrault',
                'price'          => 3500.00,
                'description'    => 'El clásico cuento infantil con ilustraciones a todo color.',
                'stock'          => 50,
                'image'          => 'libros/caperucita.jpg',
                'category'       => 'aventura',
                'age'            => 'infantil',
                'is_new'         => true,
                'discount'       => 30.00,
                'is_recommended' => false,
            ],
            [
                'title'          => 'Asesinato en el Orient Express',
                'author'         => 'Agatha Christie',
                'price'          => 10500.00,
                'description'    => 'El detective Hércules Poirot investiga un crimen en un tren atrapado por la nieve.',
                'stock'          => 14,
                'image'          => 'libros/orient-express.jpg',
                'category'       => 'misterio',
                'age'            => 'adulto',
                'is_new'         => false,
                'discount'       => 5.00,
                'is_recommended' => true,
            ],
        ];

        $posts = $this->table('books');
        $posts->insert($data)
              ->saveData();
    }
}
